config/routes.rb
Rails.application.routes.draw do
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :users, only:[:new, :create, :show]
  resources :sessions, only:[:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy]
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root to: 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image_url, PictureUploader
  validates :image_url, presence: true
  validates :sentence, length: { in: 1..2200 }
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }
  has_many :pictures
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :you_cannot_post, only: [:new, :edit, :show, :destroy]
  # before_action :set_favorite, only: [:show]

  def index
    @picture = Picture.all
    if logged_in?
      @favorite = current_user.favorites
    end
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def confirm
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    if @picture.save
      InstaMailer.insta_mailer(@picture).deliver
      redirect_to pictures_path, notice: '写真を投稿しました'
    else
      render "new"
    end

  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: '文章を編集しました'
    else
      render 'edit'
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice: '写真を削除しました'
  end

  private

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:sentence, :image_url_cache, :image_url, :user_id)
  end

  def you_cannot_post
    unless logged_in?
      redirect_to new_session_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = "ログインに失敗しました"
      render "new"
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to pictures_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    #@current_userがnilならログインしているユーザーのidをセッションから代入
    @current_user ||= User.find_by(id: session[:user_id])
    #セッションが空なら空白を代入
    # @current_user ||= {"id" => 0}
  end

  def logged_in?
    current_user.present?
    # && current_user.id != 0
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaclone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class = 'container'>
      <header class = insta-gradation>
        <div class = 'header'>
          InstaClone
        </div>
      </header>
      <div class = 'content'>
        <nav>
          <% if logged_in? %>
            <ul class = 'nav login-nav'>
              <li><%= link_to "マイページ", user_path(current_user.id) %></li>
              <li><%= link_to "新規投稿", new_picture_path %></li>
              <li><%= link_to "投稿一覧", pictures_path %></li>
              <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
            </ul>
            <% else %>
            <ul class = 'nav logout-nav'>
              <li class = 'long-nav'><%= link_to "ユーザー登録する", new_user_path %></li>
              <li><%= link_to "ログイン", new_session_path %></li>
              <li><%= link_to "投稿一覧", pictures_path %></li>
            </ul>
          <% end %>
        </nav>

        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>

        <%= yield %>
      </div>

      <footer class = 'insta-gradation'>
        <div class = 'footer'>
          <p>Instagram Clone</p>
          <p>by Ryohei Aoki</p>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with model: @picture, local: true, url: confirm_pictures_path do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @picture.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table>
    <tr class="field">
      <th><%= form.label "画像" %></th>
      <td class = 'image-form'>
        <%= form.file_field :image_url %>
        <%= form.hidden_field :image_url_cache %>
      </td>
    </tr>

    <tr>
      <th><%= form.label "文章" %></th>
      <td><%= form.text_area :sentence, class: 'sentence-area', placeholder: :"文章" %></td>
    </tr>
  </table>
  <div class="actions">
    <%= form.submit "送信", class: "btn btn-info" %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h1>確認画面</h1>

<%= form_with model: @picture, local: true do |form| %>

  <%= form.hidden_field :image_url_cache %>
  <%= form.hidden_field :sentence %>

  <%= image_tag @picture.image_url %>

  <div class = 'confirm-sentence-wrapper'>
    <p class = 'confirm-sentence'><%= @picture.sentence %></p>
  </div>

  <div class="actions">
    <%= form.submit "送信", class: "btn btn-info" %>
  </div>
<% end %>

<%= form_with(model: @picture, url: new_picture_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :image_url %>
  <%= form.hidden_field :sentence %>
  <%= form.submit "戻る", name: "back", class: "btn btn-warning" %>
<% end %>

app/views/pictures/edit.html.erb
<%= form_with model: @picture, local: true do |form| %>

  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @picture.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <%= image_tag @picture.image_url %>
    </tr>

    <tr>
      <th><%= form.label "文章" %></th>
      <td><%= form.text_area :sentence, class: 'sentence-area', placeholder: :"文章" %></td>
    </tr>
  </table>
  <div class="actions">
    <%= form.submit "送信", class: "btn btn-info" %>
  </div>
<% end %>

app/views/pictures/index.html.erb
<% @picture.each do |picture| %>
  <article class="picture-index">
    <div class = "posting-user bottom-border">
      <%= picture.user.name %>
    </div>
    <div class = "contributed-picture bottom-border">
      <%= image_tag picture.image_url %>
    </div>
    <div class = "contributed-sentence bottom-border">
      <%= picture.sentence %>
    </div>

    <% if logged_in? %>
    <div class = "index-button">
      <% if current_user.id == picture.user.id %>
        <%= link_to '編集する', edit_picture_path(picture), class: "btn btn-primary" %>
        <%= link_to '削除', picture_path(picture), method: :delete, class: "btn btn-danger" %>
      <% else %>
        <% if  @favorite.find_by(picture_id: picture.id).present? %>
          <%= link_to 'お気に入りを取り消し', favorite_path(id: @favorite.ids), method: :delete, class: "btn btn-info" %>

        <% else %>
          <%= link_to 'お気に入りに登録', favorites_path(picture_id: picture.id), method: :post, class: "btn btn-info" %>
        <% end %>
      <% end %>
    </div>
    <% end %>
  </article>
<% end %>

app/views/pictures/new.html.erb
<%= render 'form', picture: @picture %>

app/views/pictures/show.html.erb
<%= image_tag @picture.image_url %>

<%= @picture.sentence %>

<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to "いいねを取り消す", favorite_path(id: @favorite.id), method: :delete %>
  <% else %>
    <%= link_to "いいね", favorites_path(picture_id: @picture.id), method: :post %>
  <% end %>
<% end %>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <%= pluralize(@user.errors.count, "error") %>prohibited this @user from being saved
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <table>
    <tr>
      <th><%= f.label "お名前" %></th>
      <td><%= f.text_field :name,  placeholder: :"山田太郎", class: "text-area" %></td>
    </tr>

    <tr>
      <th><%= f.label "メールアドレス" %></th>
      <td><%= f.email_field :email, placeholder: "@mail.mail", class: "text-area" %></td>
    </tr>

    <tr>
      <th>
        <%= f.label "パスワード" %>
        <p class = "password-instruction" >8桁以上</p>
      </th>
      <td><%= f.password_field :password, class: "text-area" %></td>
    </tr>

    <tr>
      <th><%= f.label "パスワード確認" %></th>
      <td><%= f.password_field :password_confirmation, class: "text-area" %></td>
    </tr>
  </table>
  <%= f.submit "登録する", class: "btn btn-info" %>
<% end %>

app/views/users/show.html.erb
<p><%= @user.name %>さん、こんにちは</p>

<% if @user.favorite_pictures.present? %>
  <h4 class = 'favorite-info'>お気に入り登録した画像一覧</h4>
  <% @user.favorite_pictures.each do |picture| %>
    <article class="picture-index">
      <div class = "posting-user bottom-border">
        <%= picture.user.name %>
      </div>
      <div class = "contributed-picture bottom-border">
        <%= image_tag picture.image_url %>
      </div>
      <div class = "contributed-sentence bottom-border">
        <%= picture.sentence %>
      </div>
    </article>
  <% end %>
<%else%>
  <h4 class = 'no-favorite-info'>お気に入り登録された画像はありません。</h4>
<% end %>